"""create analyses and rep_metrics tables

Revision ID: 9138cfee5b5b
Revises: 
Create Date: 2026-03-15 22:48:36.453265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9138cfee5b5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('video_path', sa.String(length=512), nullable=True),
    sa.Column('annotated_video_path', sa.String(length=512), nullable=True),
    sa.Column('csv_path', sa.String(length=512), nullable=True),
    sa.Column('plot_path', sa.String(length=512), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rep_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('rep_index', sa.Integer(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=True),
    sa.Column('end_frame', sa.Integer(), nullable=True),
    sa.Column('min_knee_angle', sa.Float(), nullable=True),
    sa.Column('max_knee_angle', sa.Float(), nullable=True),
    sa.Column('min_hip_angle', sa.Float(), nullable=True),
    sa.Column('max_hip_angle', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rep_metrics_analysis_id'), 'rep_metrics', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rep_metrics_analysis_id'), table_name='rep_metrics')
    op.drop_table('rep_metrics')
    op.drop_table('analyses')
    # ### end Alembic commands ###
